# Generated by Django 4.2 on 2023-05-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='length',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Прямоугольный'), ('oval', 'Овальный')], default='rectangle', max_length=10),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
