<<<<<<< HEAD
# Generated by Django 4.2 on 2023-05-08 14:28
=======
# Generated by Django 4.2 on 2023-05-07 18:53
>>>>>>> da9c40775242a7755ecc010794e8325942289827

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_table_length_table_shape_table_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_table', to='order.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('triangle', 'Triangle')], default='rectangle', max_length=10),
        ),
    ]
